### ISSUE TITLE
cannot simulate caracter "@"

### ISSUE THREAD

**Issue by Pierre-Michel** [ChiHangChen/KeyboardSimulator#10]
Hello, when using the following command:

`keybd.press('@')`

I get the caracter "é" in the R console with the following warning:

`Warning message:
In keybd.press("@") :
  Button '@' will be treated as lowercase. Use 'keybd.type_string' for uppercase keyboard simulation.`

Do you have any idea to solve this issue ?
Best regards

**Comment by jeffkeller87** [comment]
Hi @Pierre-Michel, the `keybd.press` function currently simulates exactly one key press. There is no dedicated `@` key, so you are seeing this warning.

You are actually trying to simulate `Shift + 2`, which is something that the `keybd.type_string` function can do (and is what the warning message is trying to tell you).

Try this:

```
keybd.type_string("@")
```

The verbiage of the warning message isn't ideal. It suggests that the `@` symbol is an upper case `2` (or that a `2` is a lower case `@`). But it really just means that the `Shift` modifier won't be applied when using `keybd.press`.

**Comment by Pierre-Michel** [comment]
Hi @jeffkeller87 and thank you for your reply.
Using the `keybd.type_string` did not change my issue, as I am using a AZERTY keyboard and not QWERTY, is there a way to parameterize it ?
"Shift + 2" combination would generate caracter "é" in my case... and it seems that combinations using "AltGr" are not available, am I right ?
On my keyboard the good combination would be "AltGr + 0".
Best regards.

**Comment by jeffkeller87** [comment]
Yes the package was only written for QWERTY layouts and I don't have access to non-QWERTY layouts right now. But there's not much stopping us from adding other layouts like QWERTZ or AZERTY in the future. Finding a resource that details the various scan codes for those layouts would be a first step. **Please let me know if you have such a resource because I would love to add more keyboard layout support.**

You could probably find a workaround in the meantime if you can figure out which key on a QWERTY layout has the same scan code as `AltGr`. For the sake of an example, let's assume the equivalent is `alt`. Then you could do something like this:

```
keybd.press("alt", hold = TRUE)
keybd.press("0")
keybd.release("alt")
```
